// kartei, a self-hosted workspace for documents and structured data.
// Copyright (C) 2026  iderex
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! `--locked` is only a pin if something refuses a lockfile that has drifted.
//!
//! The gate builds and tests with `--locked` so that a dependency which quietly
//! resolves to something else reds the build instead of shipping. That is a flag
//! in a workflow file, and a flag is an assertion until somebody watches it
//! refuse. This test watches it, against a fixture workspace it builds itself.
//!
//! The fixture is a fixture. It is written into a temporary directory of this
//! test's own and has no dependencies, so nothing here reads this repository's
//! real lockfile and nothing here reaches the network. A test that judged the
//! real tree would prove the state of the tree on the day it ran, not the flag.
//!
//! It lives in the binary crate next to the boundary test, because both are
//! tests about the workspace as a whole rather than about a crate.

use std::path::Path;
use std::process::{Command, Output};

use kartei_testing::TempDir;

/// The fixture manifest. One package, no dependencies, so a build touches
/// nothing outside the directory it is in.
const MANIFEST: &str = r#"[package]
name = "locked-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
"#;

/// The matching lockfile.
const LOCK_MATCHING: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "locked-fixture"
version = "0.1.0"
"#;

/// The same lockfile with one character changed, which is the mistake somebody
/// actually makes: a version bumped in the manifest, or a dependency added,
/// without the lockfile being regenerated.
const LOCK_DRIFTED: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "locked-fixture"
version = "0.1.1"
"#;

/// Writes the fixture workspace and returns the path to its manifest.
fn write_fixture(root: &Path, lock: &str) -> std::path::PathBuf {
    std::fs::create_dir_all(root.join("src")).expect("the fixture directory is the test's own");
    std::fs::write(root.join("Cargo.toml"), MANIFEST).expect("writing the fixture manifest");
    std::fs::write(root.join("Cargo.lock"), lock).expect("writing the fixture lockfile");
    std::fs::write(
        root.join("src").join("lib.rs"),
        "// nothing to compile but a crate\n",
    )
    .expect("writing the fixture source");
    root.join("Cargo.toml")
}

/// Builds the fixture with `--locked`, in isolation.
///
/// `--offline` as well as `--locked`, so the leg cannot pass or fail for a
/// reason that lives on somebody else's server. The target directory is inside
/// the fixture, so the build writes nothing outside the directory this test
/// created.
fn build_locked(root: &Path, manifest: &Path) -> Output {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned());

    Command::new(cargo)
        .args(["build", "--locked", "--offline", "--manifest-path"])
        .arg(manifest)
        .env("CARGO_TARGET_DIR", root.join("target"))
        .output()
        .unwrap_or_else(|e| panic!("could not run cargo: {e}"))
}

#[test]
fn a_lockfile_that_matches_its_manifest_builds() {
    let dir = TempDir::new("locked-matching");
    let manifest = write_fixture(dir.path(), LOCK_MATCHING);

    let out = build_locked(dir.path(), &manifest);

    assert!(
        out.status.success(),
        "the control leg failed, so a red in the other leg would not be \
         attributable to the lockfile:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
}

#[test]
fn a_lockfile_that_has_drifted_reds_the_build() {
    let dir = TempDir::new("locked-drifted");
    let manifest = write_fixture(dir.path(), LOCK_DRIFTED);

    let out = build_locked(dir.path(), &manifest);
    let stderr = String::from_utf8_lossy(&out.stderr);

    assert!(
        !out.status.success(),
        "the build accepted a lockfile that does not match its manifest, so \
         --locked pins nothing:\n{stderr}"
    );
    assert!(
        stderr.contains("--locked"),
        "the build failed for a reason that is not the lockfile:\n{stderr}"
    );
}
